### PR TITLE
Fix caching issues with `update_puma_scripts` and `update_web_suite_package_scripts`

### PR DESCRIPTION
**Pull request by WilliamMcCumstie**
Previously the caching mechanism would skip updating the files if the shared config had changed. This meant `clean --purge` is required to prevent stale files.

Omnibus caching mechanism maintains an internal `git` repo which it tags at each stage of the build. This way it can analysis the build configurations and skip to the appropriate point in the build.

This unfortunately does not work particularly well for files within `opt` or `package-scripts` as they do not have a versioned source (aka `git` or `url`). Instead they need to be re-rendered on every build.

---

As the scripts are now guaranteed to be rendered, they no longer need to be checked into the git repo. Special care has been taken to ensure they appear in `extra_package_files` when required.

### CODE REVIEW

**Comment by benarmston** [comment]
Does having them checked into the git repo cause any issues?  I've gone back and forth on whether it is better to have them checked in or not (assuming both work correctly).  It's nice to be able to see exactly how they changed from the previous version.

**Comment by WilliamMcCumstie** [comment]
There are no technical limitations either way. The build will update the scripts, so the `rpm` should be accurate.

Considerations:

* Checking them in makes it easy to refer to them at the risk of them going stale, but
* Omitting them makes them hard to view (baring inspecting the `rpm`/build results).

I am partial to checking them in, but adding a hook to the build which will crash if they are updated

**Comment by benarmston** [comment]
@WilliamMcCumstie I think I've rebased this correctly on `master` could you take a quick look at it please.

**Comment by WilliamMcCumstie** [comment]
> @WilliamMcCumstie I think I've rebased this correctly on `master` could you take a quick look at it please.

The rebase LGTM

**Pull request merged**
