### PR TITLE
Update file-manager-api and login-api to use the new configuration mechanism

### PR DESCRIPTION
**Pull request by WilliamMcCumstie**
EDIT: Original PR description

I need the ability to generate alpha release packages for the `flight-web-suite` domain  changes.

`omnibus` already supports building of branches/commit hashes, so all that is needed is a way to hook in the required value. This means tagging the upstream repo is not required when generating a dev build.

---

In addition to the `alpha` release mechanism, both `login-api` and `file-manager-api` have been updated to use the new `FlightConfiguration::DSL` with a `Flight` stub.

This means the core configuration is now stored within `/opt/flight/etc` and various files within `/opt/flight/{libexec,var}`. Most of the config overrides within the builder have been removed; as they reconfigured the paths to `/opt/flight/...`. This is now done implicitly by the `Flight` stub.

---

The major addition is the "relative path message" within the core configs need to be updated. The original message contains details about `flight_ROOT` and the environment setup. These details are required in the upstream source for documentation purposes, but are needless verbose for the builder.

Once the `builder` has ran, the environment and `flight_ROOT` have been set. The config message should be updated to reflect this:

* The actual configs explicitly state the paths are expanded from `/opt/flight` (because they have to be), and
* An original copy is shipped as `/o/f/o/<app>/etc/<app>.yaml.reference` for in-depth documentation purposes only.

---

A new `flight-web-suite-utils` package has been added. It contains the `flight config` definition for setting the `flight_WEB_SUITE_domain`.

### CODE REVIEW

**Review by benarmston — CHANGES_REQUESTED** [review]
I've rebased this branch on `user-web-suites-2021.5` and adjusted the PR target branch accordingly.  That's going to allow me to test it with the other changes to the web-suite such as the automatic creation of SSL certs.

---

The `ALPHA` mechanism is a nice idea.  Let's run with it and see if it does cut down on repo package spam.

---

Having `flight-web-suite-utils` seems a little odd.  The installation process becomes:

```
yum install https://repo.openflighthpc.org/pub/centos/7/openflighthpc-release-latest.noarch.rpm
yum install flight-web-suite-utils
flight start
flight config set web-suite.domain my.domain
yum install flight-web-suite
```

I think the following might be clearer.

```
yum install https://repo.openflighthpc.org/pub/centos/7/openflighthpc-release-latest.noarch.rpm
yum install flight-starter
flight start
flight config set web-suite.domain my.domain
yum install flight-web-suite
```

But I'm not entirely sold on that either.  Let's leave it as it is for now and solicit feedback from @ColonelPanicks when its ready for acceptance testing.

---

Regarding the configuration files.

When porting `flight-cert` to the new configuration mechanism, I decided that the best solution was to duplicate the configuration into the builder and directly make whatever changes are required there.  See https://github.com/openflighthpc/openflight-omnibus-builder/pull/118 for some details.

This method has a number of advantages:

* The production config file can be read from within the builder, without having to evaluate what the software definition is doing.

* The production and dev configs can be compared using standard tools such as `diff` (or Vim's diff mode).

* Changes from one can easily be copied to the other using standard tools such as `patch` (or Vim's diff mode).

* Changes to the configuration can be tested and then copied to the builder using standard tools such as `cp`.

* Explanatory comments such as relative paths can be tailored to the particular environment the config file is going to be used in.

* The history of the config file can be determined using standard tools such as `git log`.

* The development config file doesn't have artefacts such as `>>path<<`.

It does have the disadvantage that changes to the dev config need to be copied to the production config.  I find that to be an acceptable trade off.

---

Regarding relative paths language

The language that I settled on for `flight-cert` was

> Relative paths are expanded from flight_ROOT (or the install directory, if flight_ROOT is unset).

As our RPMs don't ship with `.env.development` file, this is close enough to the truth.  Although perhaps its use of `flight_ROOT` is a little obscure.

---

Regarding the `.reference` files.

I'm not sure why they're being included.  A well commented production config added according the policy above should remove the need for it.

Including the reference file is likely to confuse people.  We've had config files live under `/opt/flight/opt/<APP>/etc/` for some time now.  People will naturally look there.  IIRC, some of our applications have shipped with a `*.yaml.reference` file that the user is expected to rename to `*.yaml` and edit.

**Comment by WilliamMcCumstie** [comment]
In regards to the install process, why wouldn't it be:

```
yum install https://repo.openflighthpc.org/pub/centos/7/openflighthpc-release-latest.noarch.rpm
yum install flight-starter flight-web-suite
flight start
flight config set web-suite.domain my.domain
```

I get that the `fligh-www` now (will?) generate a self-signed certificate on `postinst`. However this is more general bootstrapping to get it in a some-what working state.

We shouldn't be relying on the user remembering the domain needs to be set correctly _before_ installing the related packages. If we are, that's a limitation of `flight config`.

I'm getting the feeling we are relying on too much stuff happening in the `postinst` scripts so things JustWork :tm:.

**Comment by WilliamMcCumstie** [comment]
Note to future self, the `flight-www` `postinst` package needs updating to check if `flight_WEB_SUITE_domain` has been set. Otherwise it will use what ever the `hostname` setting is here:

https://github.com/openflighthpc/openflight-omnibus-builder/blob/f0bd4534ed3cfe529156765644f608e3e15b26c5/builders/flight-www/package-scripts/flight-www/postinst#L83

**Comment by benarmston** [comment]
We definitely want things to be as easy as possible to get the web suite up and running.

Unfortunately, that process is currently overly cumbersome.  To do everything without any kind of orchestration, a user would need to:

0. Install the openflight repo.
1. Install the relevant packages
2. Configure the cookie domains for some, but not all, services.
3. Start the services.
4. Configure SSL certs for a given domain.
5. Enable HTTPS support for `flight-www`.
6. Enable the services, so that they come back up after reboot.

We have a number of tools each of which focus on a single step and do a good job of each of those steps.  But the overall process is still too cumbersome and needs more orchestration.

The example you gave of how you would expect it to work, left out steps 4, 5 and 6 and glossed over step 3.  I'm going to take that as a sign that its too much of a pain to write out the entire thing; and therefore too much of a pain for users to get right every time.

Unfortunately, we have a few hurdles to overcome before we can support the kind of orchestration (and user experience that I want).

1. Configuration of the domain multiple times; ensuring they are consistent.
2. Installation of additional dependencies for Flight Desktop.
3. Requiring a trusted certificate for Flight File Manager.

---

The installation of a self-signed certificate in `flight-www`'s `postinst` is intended to be part of getting the web suite into a fully functional state.  That fully functional state will use an untrusted certificate; but as long as they, and their users, are OK with that, that's fine.

---

Using post installation scripts to orchestrate much of this work is a reasonable idea.  Perhaps not the ideal solution.  A better solution would likely be to add some orchestration tooling to `flight-web-suite-utils` such that the process becomes:

```
yum install https://repo.openflighthpc.org/pub/centos/7/openflighthpc-release-latest.noarch.rpm
yum install flight-web-suite
flight start
flight web-suite set-domain my.domain
flight web-suite start
flight web-suite enable
```

`flight web-suite` could then hide the details of 1) which services it starts; 2) which services get reconfigured when the domain changes; 3) other things that need to happen when the domain changes.

However, there are issues that need considering with such a tool.  The above, makes no mention of SSL or HTTPS.  Is that too much information hiding?  The above separates starting from enabling.  Is that too little information hiding?  Does it make sense to have both `flight service start ...` and `flight web-suite start`?  Is having both going to cause confusion?  There are similar questions for `flight web-suite set-domain` vs `flight config set web-suite.domain`.

All of those questions are outside the scope of this work.  For now we need a means to share the domain setting, in a way that supports the three use cases given on the trello card.

**Comment by WilliamMcCumstie** [comment]
> The `ALPHA` mechanism is a nice idea. Let's run with it and see if it does cut down on repo package spam.

:+1: 

> Having `flight-web-suite-utils` seems a little odd. The installation process becomes:

I've added `flight-web-suite-utils` as a runtime dependency to `flight-starter`. This was the fastest way to ensure it is available on `yum install flight-starter` and `yum install flight-websuite`**. We can decide the future of `flight-web-suite-utils` at a future date.

\** `flight-web-suite` does not have a direct dependency on `flight-stater`, but there *may* be a transient. `flight-web-sutie-utils` ensure it works either way.

> Regarding the configuration files.
> 
> When porting `flight-cert` to the new configuration mechanism, I decided that the best solution was to duplicate the configuration into the builder and directly make whatever changes are required there. See #118 for some details.

I haven't done this yet. After changing the wording in the core configs, I know longer felt the need to change it. This means `/opt/flight/etc/<app>.yaml` is a carbon copy of the original. For the time being, copying it from the source is sufficient.

This can be revisited if an when an alteration is required.

> Regarding relative paths language
> 
> The language that I settled on for `flight-cert` was
> 
> > Relative paths are expanded from flight_ROOT (or the install directory, if flight_ROOT is unset).

Updated.

> Regarding the `.reference` files.
> 
> I'm not sure why they're being included. A well commented production config added according the policy above should remove the need for it.

Removed.

**Comment by benarmston** [comment]
> I haven't done this yet. After changing the wording in the core configs, I know longer felt the need to change it. This means /opt/flight/etc/<app>.yaml is a carbon copy of the original. For the time being, copying it from the source is sufficient.

That's good.  This is where I'd like to be for many of our apps, hence the support for relative paths from `Flight.root`.

**Comment by benarmston** [comment]
Something isn't quite right with this @WilliamMcCumstie.  I have a job with results 

```
[vagrant@chead1 flight-job]$ /opt/flight/bin/ruby ./bin/job  ls-job-results Ynr_mtlJ 
test.output
[vagrant@chead1 flight-job]$ 
[vagrant@chead1 flight-job]$ 
[vagrant@chead1 flight-job]$ /opt/flight/bin/ruby ./bin/job  info-job Ynr_mtlJ --include result_files --json | /opt/flight/opt/jq/bin/jq .result_files
[
  {
    "file": "/home/vagrant/simple.sh-outputs/4/test.output",
    "size": 70
  }
]
[vagrant@chead1 flight-job]$ 

```

And yet the webapp informs me I have none.

image

The relevant portion of the puma logs.

```
I, [2021-06-24T14:39:35.299442 #16680]  INFO -- : 
COMMAND: /code/flight-job-script-service/api/libexec/job info-job Ynr_mtlJ --json --include script
USER: vagrant
PID: 17786
STATUS: 0
I, [2021-06-24T14:39:35.300666 #16680]  INFO -- : Lazy loading related script: test (script: Ynr_mtlJ)
10.0.2.2 - - [24/Jun/2021:14:39:35 +0000] "GET /v0/jobs/Ynr_mtlJ?include=script HTTP/1.1" 200 3344 1.2246
10.0.2.2 - - [24/Jun/2021:14:39:35 +0000] "GET /v0/jobs/Ynr_mtlJ?include=script HTTP/1.0" 200 3344 1.2247
I, [2021-06-24T14:39:36.394124 #16680]  INFO -- : 
COMMAND: /code/flight-job-script-service/api/libexec/job info-job Ynr_mtlJ --json --include ""
USER: vagrant
PID: 17802
STATUS: 0
10.0.2.2 - - [24/Jun/2021:14:39:36 +0000] "GET /v0/jobs/Ynr_mtlJ/output-files HTTP/1.1" 200 1025 1.0670
10.0.2.2 - - [24/Jun/2021:14:39:36 +0000] "GET /v0/jobs/Ynr_mtlJ/output-files HTTP/1.0" 200 1025 1.0671
I, [2021-06-24T14:39:37.640499 #16680]  INFO -- : 
COMMAND: /code/flight-job-script-service/api/libexec/job info-job Ynr_mtlJ --json --include ""
USER: vagrant
PID: 17817
STATUS: 0
E, [2021-06-24T14:39:37.642159 #16680] ERROR -- : The job 'Ynr_mtlJ' was unexpectedly loaded without its results_files
10.0.2.2 - - [24/Jun/2021:14:39:37 +0000] "GET /v0/jobs/Ynr_mtlJ/result-files HTTP/1.1" 200 83 2.3049
10.0.2.2 - - [24/Jun/2021:14:39:37 +0000] "GET /v0/jobs/Ynr_mtlJ/result-files HTTP/1.0" 200 83 2.3050


```

**Comment by benarmston** [comment]
I'm going to merge this to `user-web-suites-2021.5` and deal with any integration issues altogether.  FWIW this LGTM.

**Pull request merged**
