### PR TITLE
Script to setup HTTPs for flight-service-www

### PR DESCRIPTION
**Pull request by benarmston**
This PR adds a script to setup HTTPs for `flight-service-www`.  It 1) generates self-signed SSL certificates; 2) copies them to the correct location; 3) configures nginx to use HTTPs; and 4) restarts the `www` service.

The script is added to `/opt/flight/bin/` and is expected to be called as `flexec flight-service-www-https enable`.

I have a couple of questions regarding this:

 1. Is the `/opt/flight/bin/` the correct location for this script?  Or should it be somewhere in `/opt/flight/libexec/`?

 2. The certificate is valid for 365 days.  Do you have any reason that this should be different?

### CODE REVIEW

**Comment by mjtko** [comment]
Hmm, it's a good question about putting this in `/opt/flight/bin`. I don't think anything else we've created  up to this point has had any real "entry point" scripts and commands are always proceesed via the `flight` command.

Maybe we could have a `libexec/commands/www` and do it via that, e.g.:

```
flight www enable-https
flight www disable-https
```

The command could also then be marked as root-only so it wouldn't be shown to users.

Longer-term we could move this towards using `flight service configure` but, as you've rightly identified, that's going to require some additional work on `flight-service` to make feasible.

**Comment by mjtko** [comment]
Might as well make it 3650 days while we're at it. I don't think having a self-signed cert valid for 10 years is any worse than having one valid for 1 year. :)

**Comment by benarmston** [comment]
I've addressed the points you've raised @mjtko.  I think it would probably be a good idea for you to check that I've understood how to mark the command as root-only correctly.

**Comment by benarmston** [comment]
I've addressed the points you've raised @mjtko.  Do you want to take another look?

**Pull request merged**
